[package]
name = "trip_gigo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#crate-type = ["cdylib"]

[dependencies]
des = "0.8.1"
#wasm-bindgen = "0.2.89"